export const RESERVATIONS = [
    {
        reservationId: '80201809',
        colorIndicator: '#d87e00',
        paymentType: 'CC',
        plannerStatus: 'Active',
        reservationStatus: 'lease',
        tripType: 'oneway',
        leaseType: 'Short Term',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '066610',
                locationType: 'District',
                locationName: 'Knoxville',
                locationAddress: {
                    addressLine1: '864 Cypress Court',
                    addressLine2: 'C/O John Smith',
                    city: 'Chickasaw',
                    stateProvince: 'LA',
                    postalCode: '27601',
                    country: 'USA',
                },
                outboundCode: '671537',
                region: 'Agent',
                utcOffset: -6,
                dayLight: true,
                regionName: 'Jackson',
                area: 'Agent',
                areaName: 'Eugene',
                reportingLocationCode: '455670',
                reportingLocationName: 'Fargo',
                branch: '7873',
                branchName: 'Fargo',
                phoneNumber: '(410) 555-0187',
            },
            pickUpTime: '10:24:12',
            pickUpDate: '2026-02-27',
            pickUpUTCTimestamp: '2026-02-27 10:24:12.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '078945',
                locationType: 'Branch',
                locationName: 'Dallas',
                locationAddress: {
                    addressLine1: '112 Main Street',
                    addressLine2: '',
                    city: 'Dallas',
                    stateProvince: 'TX',
                    postalCode: '75201',
                    country: 'USA',
                },
                outboundCode: '229911',
                region: 'South',
                utcOffset: -6,
                dayLight: true,
                regionName: 'Texas',
                area: 'Metro',
                areaName: 'Dallas',
                reportingLocationCode: '889900',
                reportingLocationName: 'Dallas Central',
                branch: '4451',
                branchName: 'Dallas',
                phoneNumber: '(214) 555-0192',
            },
            expectedDropOffDate: '2026-06-20',
            expectedDropOffTime: '15:00:00',
            expectedDropOffUTCTimestamp: '2026-06-20 15:00:00.000',
        },
        assignedUnit: {
            unitNumber: 'TR-1001',
            unitClass: '1315',
            unitType: '2026',
            unitStatus: 'Available Now',
            colorIndicator: 'yellow',
            source: 'Penske',
            unitDescription: "48' TRAILER",
            owningLocationCode: '579533',
            owningCorp: 'HPTL',
            physicalLocationCode: '515149',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '84712435',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '87199489',
                dueInDate: '2026-06-20',
                contractStatus: 'Active',
                contractType: '',
            },
            preventiveMaintenanceDate: '2026-06-22',
        },
        assignedTowUnit: {
            unitNumber: 'TW-2211',
            unitClass: '2026',
            unitType: '1315',
            unitStatus: 'Available Now',
            description: '12FT SAG LIGHT HICUBE',
            physicalLocationCode: '314229',
            physicalCorp: 'HPTL',
            owningLocationCode: '530133',
            hikeInfo: {
                hikeReqNumber: '89207555',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '81518452',
                dueInDate: '2026-06-22',
                contractStatus: 'Inactive',
                contractType: 'HPTL',
            },
            preventiveMaintenanceDate: '2026-06-23',
            source: 'Penske',
            owningCorp: 'HPTL',
        },
        rentalType: 'Consumer',
        consumerCustomer: {
            firstName: 'David',
            lastName: 'Martinez',
            phoneNumber: '(909) 555-0173',
            email: 'david.martinez@example.com',
            insuranceStatus: 'Inactive',
        },
        isCustomerContacted: true,
        cashDeposit: false,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: '',
    },

    {
        reservationId: '80201810',
        colorIndicator: '#a92323',
        paymentType: 'CA',
        plannerStatus: 'Inactive',
        reservationStatus: 'confirmed',
        tripType: 'roundtrip',
        leaseType: 'Long Term',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '089321',
                locationType: 'Branch',
                locationName: 'Chicago',
                locationAddress: {
                    addressLine1: '22 Lake Shore Dr',
                    addressLine2: '',
                    city: 'Chicago',
                    stateProvince: 'IL',
                    postalCode: '60601',
                    country: 'USA',
                },
                outboundCode: '887766',
                region: 'Midwest',
                utcOffset: -6,
                dayLight: true,
                regionName: 'Illinois',
                area: 'Urban',
                areaName: 'Chicago',
                reportingLocationCode: '334455',
                reportingLocationName: 'Chicago Hub',
                branch: '9981',
                branchName: 'Chicago',
                phoneNumber: '(312) 555-0144',
            },
            pickUpTime: '08:00:00',
            pickUpDate: '2026-02-23',
            pickUpUTCTimestamp: '2026-02-23 08:00:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '089321',
                locationType: 'Branch',
                locationName: 'Chicago',
                locationAddress: {
                    addressLine1: '22 Lake Shore Dr',
                    addressLine2: '',
                    city: 'Chicago',
                    stateProvince: 'IL',
                    postalCode: '60601',
                    country: 'USA',
                },
                outboundCode: '887766',
                region: 'Midwest',
                utcOffset: -6,
                dayLight: true,
                regionName: 'Illinois',
                area: 'Urban',
                areaName: 'Chicago',
                reportingLocationCode: '334455',
                reportingLocationName: 'Chicago Hub',
                branch: '9981',
                branchName: 'Chicago',
                phoneNumber: '(312) 555-0144',
            },
            expectedDropOffDate: '2026-07-05',
            expectedDropOffTime: '12:00:00',
            expectedDropOffUTCTimestamp: '2026-07-05 12:00:00.000',
        },
        assignedUnit: {
            unitNumber: 'TR-2002',
            unitClass: '1400',
            unitType: '2030',
            unitStatus: 'Out-commercial',
            source: 'Penske',
            unitDescription: "53' TRAILER", 
            owningLocationCode: '998811',
            owningCorp: 'HPTL',
            physicalLocationCode: '998811',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '90112233',
                hikeStatus: 'Pending',
            },
            contractInfo: {
                contractId: '99887766',
                dueInDate: '2026-07-06',
                contractStatus: 'Inactive',
                contractType: '',
            },
            preventiveMaintenanceDate: '2026-07-10',
        },
        assignedTowUnit: null,
        rentalType: 'Commercial',
        consumerCustomer: {
            firstName: 'Sarah',
            lastName: 'Connor',
            phoneNumber: '(773) 555-0199',
            email: 'sarah.connor@example.com',
            insuranceStatus: 'Active',
        },
        isCustomerContacted: false,
        cashDeposit: true,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: 'GPS',
    },

    {
        reservationId: '80201811',
        colorIndicator: '#012084',
        paymentType: 'CC',
        plannerStatus: 'Active',
        reservationStatus: 'waitlist',
        tripType: 'oneway',
        leaseType: 'Short Term',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '112233',
                locationType: 'Branch',
                locationName: 'Phoenix',
                locationAddress: {
                    addressLine1: '77 Desert Road',
                    addressLine2: '',
                    city: 'Phoenix',
                    stateProvince: 'AZ',
                    postalCode: '85001',
                    country: 'USA',
                },
                outboundCode: '445566',
                region: 'West',
                utcOffset: -7,
                dayLight: false,
                regionName: 'Arizona',
                area: 'Metro',
                areaName: 'Phoenix',
                reportingLocationCode: '991122',
                reportingLocationName: 'Phoenix Hub',
                branch: '3311',
                branchName: 'Phoenix',
                phoneNumber: '(602) 555-0101',
            },
            pickUpTime: '09:15:00',
            pickUpDate: '2026-02-25',
            pickUpUTCTimestamp: '2026-02-25 09:15:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '445566',
                locationType: 'Branch',
                locationName: 'Las Vegas',
                locationAddress: {
                    addressLine1: '900 Strip Blvd',
                    addressLine2: '',
                    city: 'Las Vegas',
                    stateProvince: 'NV',
                    postalCode: '89101',
                    country: 'USA',
                },
                outboundCode: '778899',
                region: 'West',
                utcOffset: -8,
                dayLight: true,
                regionName: 'Nevada',
                area: 'Tourism',
                areaName: 'Vegas',
                reportingLocationCode: '882211',
                reportingLocationName: 'Vegas Central',
                branch: '2244',
                branchName: 'Las Vegas',
                phoneNumber: '(702) 555-0199',
            },
            expectedDropOffDate: '2026-06-22',
            expectedDropOffTime: '13:30:00',
            expectedDropOffUTCTimestamp: '2026-06-22 13:30:00.000',
        },
        assignedUnit: {
            unitNumber: 'TR-3101',
            unitClass: '1315',
            unitType: '2026',
            unitStatus: 'Available Now',
            source: 'Penske',
            unitDescription: "48' TRAILER",
            owningLocationCode: '112233',
            owningCorp: 'HPTL',
            physicalLocationCode: '112233',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '90001111',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '45001122',
                dueInDate: '2026-06-22',
                contractStatus: 'Active',
                contractType: '',
            },
            preventiveMaintenanceDate: '2026-06-25',
        },
        assignedTowUnit: null,
        rentalType: 'Consumer',
        consumerCustomer: {
            firstName: 'Michael',
            lastName: 'Brown',
            phoneNumber: '(480) 555-0188',
            email: 'michael.brown@example.com',
            insuranceStatus: 'Active',
        },
        isCustomerContacted: true,
        cashDeposit: false,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: 'Dolly',
    },

    {
        reservationId: '80201812',
        colorIndicator: '#d87e00',
        paymentType: 'CA',
        plannerStatus: 'Inactive',
        reservationStatus: 'lease',
        tripType: 'roundtrip',
        leaseType: 'Long Term',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '778899',
                locationType: 'District',
                locationName: 'Atlanta',
                locationAddress: {
                    addressLine1: '45 Peachtree St',
                    addressLine2: '',
                    city: 'Atlanta',
                    stateProvince: 'GA',
                    postalCode: '30301',
                    country: 'USA',
                },
                outboundCode: '123789',
                region: 'South',
                utcOffset: -5,
                dayLight: true,
                regionName: 'Georgia',
                area: 'Metro',
                areaName: 'Atlanta',
                reportingLocationCode: '554433',
                reportingLocationName: 'Atlanta Hub',
                branch: '7788',
                branchName: 'Atlanta',
                phoneNumber: '(404) 555-0166',
            },
            pickUpTime: '07:00:00',
            pickUpDate: '2026-02-26',
            pickUpUTCTimestamp: '2026-02-26 07:00:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '778899',
                locationType: 'District',
                locationName: 'Atlanta',
                locationAddress: {
                    addressLine1: '45 Peachtree St',
                    addressLine2: '',
                    city: 'Atlanta',
                    stateProvince: 'GA',
                    postalCode: '30301',
                    country: 'USA',
                },
                outboundCode: '123789',
                region: 'South',
                utcOffset: -5,
                dayLight: true,
                regionName: 'Georgia',
                area: 'Metro',
                areaName: 'Atlanta',
                reportingLocationCode: '554433',
                reportingLocationName: 'Atlanta Hub',
                branch: '7788',
                branchName: 'Atlanta',
                phoneNumber: '(404) 555-0166',
            },
            expectedDropOffDate: '2026-07-10',
            expectedDropOffTime: '16:00:00',
            expectedDropOffUTCTimestamp: '2026-07-10 16:00:00.000',
        },
        assignedUnit: {
            unitNumber: 'TR-4500',
            unitClass: '1500',
            unitType: '2035',
            unitStatus: 'Not Assigned',
            source: 'Penske',
            unitDescription: "53' TRAILER",
            owningLocationCode: '778899',
            owningCorp: 'HPTL',
            physicalLocationCode: '778899',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '99887711',
                hikeStatus: 'Pending',
            },
            contractInfo: {
                contractId: '22334455',
                dueInDate: '2026-07-12',
                contractStatus: 'Inactive',
                contractType: '',
            },
            preventiveMaintenanceDate: '2026-07-15',
        },
        assignedTowUnit: null,
        rentalType: 'Commercial',
        consumerCustomer: {
            firstName: 'Angela',
            lastName: 'Watson',
            phoneNumber: '(678) 555-0122',
            email: 'angela.watson@example.com',
            insuranceStatus: 'Inactive',
        },
        isCustomerContacted: false,
        cashDeposit: true,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: '',
    },

    {
        reservationId: '80201813',
        colorIndicator: '#a92323',
        paymentType: 'CC',
        plannerStatus: 'Active',
        reservationStatus: 'confirmed',
        tripType: 'oneway',
        leaseType: 'Short Term',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '990011',
                locationType: 'Branch',
                locationName: 'Seattle',
                locationAddress: {
                    addressLine1: '88 Pine Street',
                    addressLine2: '',
                    city: 'Seattle',
                    stateProvince: 'WA',
                    postalCode: '98101',
                    country: 'USA',
                },
                outboundCode: '564738',
                region: 'Northwest',
                utcOffset: -8,
                dayLight: true,
                regionName: 'Washington',
                area: 'Metro',
                areaName: 'Seattle',
                reportingLocationCode: '221199',
                reportingLocationName: 'Seattle Hub',
                branch: '6611',
                branchName: 'Seattle',
                phoneNumber: '(206) 555-0145',
            },
            pickUpTime: '11:00:00',
            pickUpDate: '2026-02-24',
            pickUpUTCTimestamp: '2026-02-24 11:00:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '334455',
                locationType: 'Branch',
                locationName: 'Portland',
                locationAddress: {
                    addressLine1: '19 River Road',
                    addressLine2: '',
                    city: 'Portland',
                    stateProvince: 'OR',
                    postalCode: '97201',
                    country: 'USA',
                },
                outboundCode: '998811',
                region: 'Northwest',
                utcOffset: -8,
                dayLight: true,
                regionName: 'Oregon',
                area: 'Metro',
                areaName: 'Portland',
                reportingLocationCode: '110022',
                reportingLocationName: 'Portland Hub',
                branch: '4411',
                branchName: 'Portland',
                phoneNumber: '(503) 555-0111',
            },
            expectedDropOffDate: '2026-08-03',
            expectedDropOffTime: '10:00:00',
            expectedDropOffUTCTimestamp: '2026-08-03 10:00:00.000',
        },
        assignedUnit: {
            unitNumber: 'TR-7811',
            unitClass: '1315',
            unitType: '2026',
            unitStatus: 'Available Now',
            source: 'Penske',
            unitDescription: "48' TRAILER",
            owningLocationCode: '990011',
            owningCorp: 'HPTL',
            physicalLocationCode: '990011',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '55443322',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '66778899',
                dueInDate: '2026-08-03',
                contractStatus: 'Active',
                contractType: '',
            },
            preventiveMaintenanceDate: '2026-08-05',
        },
        assignedTowUnit: null,
        rentalType: 'Consumer',
        consumerCustomer: {
            firstName: 'Jason',
            lastName: 'Miller',
            phoneNumber: '(425) 555-0177',
            email: 'jason.miller@example.com',
            insuranceStatus: 'Active',
        },
        isCustomerContacted: true,
        cashDeposit: false,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: 'Blankets',
    },

    {
        reservationId: '80201814',
        colorIndicator: '#012084',
        paymentType: 'CC',
        plannerStatus: 'Active',
        reservationStatus: 'waitlist',
        tripType: 'roundtrip',
        leaseType: 'Short Term',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '556677',
                locationType: 'Branch',
                locationName: 'San Diego',
                locationAddress: {
                    addressLine1: '321 Harbor Drive',
                    addressLine2: '',
                    city: 'San Diego',
                    stateProvince: 'CA',
                    postalCode: '92101',
                    country: 'USA',
                },
                outboundCode: '998877',
                region: 'West',
                utcOffset: -8,
                dayLight: true,
                regionName: 'California',
                area: 'Coastal',
                areaName: 'San Diego',
                reportingLocationCode: '443322',
                reportingLocationName: 'San Diego Hub',
                branch: '8899',
                branchName: 'San Diego',
                phoneNumber: '(619) 555-0133',
            },
            pickUpTime: '06:45:00',
            pickUpDate: '2026-02-26',
            pickUpUTCTimestamp: '2026-02-26 06:45:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '556677',
                locationType: 'Branch',
                locationName: 'San Diego',
                locationAddress: {
                    addressLine1: '321 Harbor Drive',
                    addressLine2: '',
                    city: 'San Diego',
                    stateProvince: 'CA',
                    postalCode: '92101',
                    country: 'USA',
                },
                outboundCode: '998877',
                region: 'West',
                utcOffset: -8,
                dayLight: true,
                regionName: 'California',
                area: 'Coastal',
                areaName: 'San Diego',
                reportingLocationCode: '443322',
                reportingLocationName: 'San Diego Hub',
                branch: '8899',
                branchName: 'San Diego',
                phoneNumber: '(619) 555-0133',
            },
            expectedDropOffDate: '2026-02-07',
            expectedDropOffTime: '18:00:00',
            expectedDropOffUTCTimestamp: '2026-02-07 18:00:00.000',
        },
        assignedUnit: {
            unitNumber: 'TR-9001',
            unitClass: '1400',
            unitType: '2030',
            unitStatus: 'Out-commercial',
            source: 'Penske',
            unitDescription: "53' TRAILER",
            owningLocationCode: '556677',
            owningCorp: 'HPTL',
            physicalLocationCode: '556677',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '11223344',
                hikeStatus: 'Pending',
            },
            contractInfo: {
                contractId: '99880011',
                dueInDate: '2026-08-16',
                contractStatus: 'Inactive',
                contractType: '',
            },
            preventiveMaintenanceDate: '2026-08-18',
        },
        assignedTowUnit: null,
        rentalType: 'Commercial',
        consumerCustomer: {
            firstName: 'Robert',
            lastName: 'Henderson',
            phoneNumber: '(858) 555-0184',
            email: 'robert.henderson@example.com',
            insuranceStatus: 'Active',
        },
        isCustomerContacted: false,
        cashDeposit: true,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: 'Lift Gate',
    },

    {
        reservationId: '80201815',
        colorIndicator: '#d87e00',
        paymentType: 'CA',
        plannerStatus: 'Inactive',
        reservationStatus: 'lease',
        tripType: 'oneway',
        leaseType: 'Long Term',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '334411',
                locationType: 'District',
                locationName: 'Denver',
                locationAddress: {
                    addressLine1: '100 Mountain View Rd',
                    addressLine2: '',
                    city: 'Denver',
                    stateProvince: 'CO',
                    postalCode: '80202',
                    country: 'USA',
                },
                outboundCode: '665544',
                region: 'Mountain',
                utcOffset: -7,
                dayLight: true,
                regionName: 'Colorado',
                area: 'Metro',
                areaName: 'Denver',
                reportingLocationCode: '221133',
                reportingLocationName: 'Denver Hub',
                branch: '7744',
                branchName: 'Denver',
                phoneNumber: '(303) 555-0129',
            },
            pickUpTime: '14:30:00',
            pickUpDate: '2026-02-25',
            pickUpUTCTimestamp: '2026-02-25 14:30:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '445599',
                locationType: 'Branch',
                locationName: 'Salt Lake City',
                locationAddress: {
                    addressLine1: '55 Canyon Blvd',
                    addressLine2: '',
                    city: 'Salt Lake City',
                    stateProvince: 'UT',
                    postalCode: '84101',
                    country: 'USA',
                },
                outboundCode: '990088',
                region: 'Mountain',
                utcOffset: -7,
                dayLight: true,
                regionName: 'Utah',
                area: 'Metro',
                areaName: 'SLC',
                reportingLocationCode: '880099',
                reportingLocationName: 'SLC Hub',
                branch: '6655',
                branchName: 'Salt Lake City',
                phoneNumber: '(801) 555-0170',
            },
            expectedDropOffDate: '2026-09-05',
            expectedDropOffTime: '11:00:00',
            expectedDropOffUTCTimestamp: '2026-09-05 11:00:00.000',
        },
        assignedUnit: {
            unitNumber: 'TR-7755',
            unitClass: '1500',
            unitType: '2040',
            unitStatus: 'Available Now',
            source: 'Penske',
            unitDescription: "40' BOX TRUCK",
            owningLocationCode: '334411',
            owningCorp: 'HPTL',
            physicalLocationCode: '334411',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '55667788',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '33221100',
                dueInDate: '2026-09-05',
                contractStatus: 'Active',
                contractType: '',
            },
            preventiveMaintenanceDate: '2026-09-07',
        },
        assignedTowUnit: null,
        rentalType: 'Consumer',
        consumerCustomer: {
            firstName: 'Emily',
            lastName: 'Clark',
            phoneNumber: '(720) 555-0165',
            email: 'emily.clark@example.com',
            insuranceStatus: 'Inactive',
        },
        isCustomerContacted: true,
        cashDeposit: false,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: '',
    },

    {
        reservationId: '80201816',
        colorIndicator: '#a92323',
        paymentType: 'CC',
        plannerStatus: 'Active',
        reservationStatus: 'confirmed',
        tripType: 'oneway',
        leaseType: 'Short Term',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '998877',
                locationType: 'Branch',
                locationName: 'Boston',
                locationAddress: {
                    addressLine1: '12 Freedom Trail',
                    addressLine2: '',
                    city: 'Boston',
                    stateProvince: 'MA',
                    postalCode: '02108',
                    country: 'USA',
                },
                outboundCode: '554433',
                region: 'Northeast',
                utcOffset: -5,
                dayLight: true,
                regionName: 'Massachusetts',
                area: 'Metro',
                areaName: 'Boston',
                reportingLocationCode: '667788',
                reportingLocationName: 'Boston Hub',
                branch: '1122',
                branchName: 'Boston',
                phoneNumber: '(617) 555-0190',
            },
            pickUpTime: '08:20:00',
            pickUpDate: '2026-02-23',
            pickUpUTCTimestamp: '2026-02-23 08:20:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '223344',
                locationType: 'Branch',
                locationName: 'New York',
                locationAddress: {
                    addressLine1: '500 Broadway',
                    addressLine2: '',
                    city: 'New York',
                    stateProvince: 'NY',
                    postalCode: '10012',
                    country: 'USA',
                },
                outboundCode: '110022',
                region: 'Northeast',
                utcOffset: -5,
                dayLight: true,
                regionName: 'New York',
                area: 'Metro',
                areaName: 'NYC',
                reportingLocationCode: '334455',
                reportingLocationName: 'NYC Hub',
                branch: '5566',
                branchName: 'New York',
                phoneNumber: '(212) 555-0181',
            },
            expectedDropOffDate: '2026-09-14',
            expectedDropOffTime: '09:30:00',
            expectedDropOffUTCTimestamp: '2026-09-14 09:30:00.000',
        },
        assignedUnit: {
            unitNumber: 'TR-8822',
            unitClass: '1315',
            unitType: '2026',
            unitStatus: 'Available Now',
            source: 'Penske',
            unitDescription: "48' TRAILER",
            owningLocationCode: '998877',
            owningCorp: 'HPTL',
            physicalLocationCode: '998877',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '77889900',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '44556677',
                dueInDate: '2026-09-14',
                contractStatus: 'Active',
                contractType: '',
            },
            preventiveMaintenanceDate: '2026-09-16',
        },
        assignedTowUnit: null,
        rentalType: 'Consumer',
        consumerCustomer: {
            firstName: 'Thomas',
            lastName: 'Reed',
            phoneNumber: '(781) 555-0142',
            email: 'thomas.reed@example.com',
            insuranceStatus: 'Active',
        },
        isCustomerContacted: true,
        cashDeposit: false,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: 'Hand Truck',
    },

    {
        reservationId: '80201820',
        colorIndicator: '#012084',
        paymentType: 'CA',
        plannerStatus: 'Active',
        reservationStatus: 'waitlist',
        tripType: 'roundtrip',
        leaseType: 'short',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '045211',
                locationType: 'Branch',
                locationName: 'Dallas',
                locationAddress: {
                    addressLine1: '221 Main Street',
                    addressLine2: '',
                    city: 'Dallas',
                    stateProvince: 'TX',
                    postalCode: '75201',
                    country: 'USA',
                },
                outboundCode: '883421',
                region: 'South',
                utcOffset: -6,
                dayLight: true,
                regionName: 'Texas',
                area: 'Metro',
                areaName: 'Dallas Metro',
                reportingLocationCode: '990121',
                reportingLocationName: 'Dallas HQ',
                branch: '1021',
                branchName: 'Dallas',
                phoneNumber: '(214) 555-0123',
            },
            pickUpTime: '09:15:00',
            pickUpDate: '2026-02-27',
            pickUpUTCTimestamp: '2026-02-27 09:15:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '078991',
                locationType: 'Branch',
                locationName: 'Houston',
                locationAddress: {
                    addressLine1: '90 Bay Area Blvd',
                    addressLine2: '',
                    city: 'Houston',
                    stateProvince: 'TX',
                    postalCode: '77058',
                    country: 'USA',
                },
                outboundCode: '772341',
                region: 'South',
                utcOffset: -6,
                dayLight: true,
                regionName: 'Texas',
                area: 'Metro',
                areaName: 'Houston Metro',
                reportingLocationCode: '770011',
                reportingLocationName: 'Houston Central',
                branch: '2023',
                branchName: 'Houston',
                phoneNumber: '(713) 555-0181',
            },
            expectedDropOffDate: '2026-07-05',
            expectedDropOffTime: '16:30:00',
            expectedDropOffUTCTimestamp: '2026-07-05 16:30:00.000',
        },
        assignedUnit: {
            unitNumber: 'TX-88231',
            unitClass: '1710',
            unitType: '3021',
            unitStatus: 'Available Now',
            source: 'Penske',
            unitDescription: "26' BOX TRUCK",
            owningLocationCode: '045211',
            owningCorp: 'HPTL',
            physicalLocationCode: '045211',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '11223344',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '99881122',
                dueInDate: '2026-07-05',
                contractStatus: 'Active',
                contractType: 'Consumer',
            },
            preventiveMaintenanceDate: '2026-07-10',
        },
        assignedTowUnit: {
            unitNumber: 'TW-55321',
            unitClass: '1210',
            unitType: '4411',
            unitStatus: 'Not Assigned',
            description: 'AUTO TRANSPORT',
            physicalLocationCode: '045211',
            physicalCorp: 'HPTL',
            owningLocationCode: '045211',
            hikeInfo: {
                hikeReqNumber: '33221199',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '55443322',
                dueInDate: '2026-07-05',
                contractStatus: 'Active',
                contractType: 'Consumer',
            },
            preventiveMaintenanceDate: '2026-07-12',
            source: 'Penske',
            owningCorp: 'HPTL',
        },
        rentalType: 'Consumer',
        consumerCustomer: {
            firstName: 'Emily',
            lastName: 'Watson',
            phoneNumber: '(469) 555-0198',
            email: 'emily.watson@example.com',
            insuranceStatus: 'Active',
        },
        isCustomerContacted: true,
        cashDeposit: true,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: 'Dolly',
    },

    {
        reservationId: '80201821',
        colorIndicator: '#d87e00',
        paymentType: 'CC',
        plannerStatus: 'Inactive',
        reservationStatus: 'lease',
        tripType: 'oneway',
        leaseType: 'long',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '091221',
                locationType: 'District',
                locationName: 'Phoenix',
                locationAddress: {
                    addressLine1: '700 Desert Road',
                    addressLine2: '',
                    city: 'Phoenix',
                    stateProvince: 'AZ',
                    postalCode: '85001',
                    country: 'USA',
                },
                outboundCode: '998122',
                region: 'West',
                utcOffset: -7,
                dayLight: false,
                regionName: 'Arizona',
                area: 'Desert',
                areaName: 'Phoenix Area',
                reportingLocationCode: '850099',
                reportingLocationName: 'Phoenix Ops',
                branch: '3099',
                branchName: 'Phoenix',
                phoneNumber: '(602) 555-0144',
            },
            pickUpTime: '13:00:00',
            pickUpDate: '2026-02-24',
            pickUpUTCTimestamp: '2026-02-24 13:00:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '065431',
                locationType: 'Branch',
                locationName: 'Las Vegas',
                locationAddress: {
                    addressLine1: '400 Strip Ave',
                    addressLine2: '',
                    city: 'Las Vegas',
                    stateProvince: 'NV',
                    postalCode: '89109',
                    country: 'USA',
                },
                outboundCode: '332211',
                region: 'West',
                utcOffset: -7,
                dayLight: true,
                regionName: 'Nevada',
                area: 'Metro',
                areaName: 'Vegas Metro',
                reportingLocationCode: '891011',
                reportingLocationName: 'Vegas Central',
                branch: '4501',
                branchName: 'Las Vegas',
                phoneNumber: '(702) 555-0177',
            },
            expectedDropOffDate: '2026-08-14',
            expectedDropOffTime: '12:00:00',
            expectedDropOffUTCTimestamp: '2026-08-14 12:00:00.000',
        },
        assignedUnit: {
            unitNumber: 'AZ-77412',
            unitClass: '2010',
            unitType: '5510',
            unitStatus: 'Out-commercial',
            source: 'Penske',
            unitDescription: "20' BOX TRUCK",
            owningLocationCode: '091221',
            owningCorp: 'HPTL',
            physicalLocationCode: '091221',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '66554433',
                hikeStatus: 'Pending',
            },
            contractInfo: {
                contractId: '22119988',
                dueInDate: '2026-08-14',
                contractStatus: 'Inactive',
                contractType: 'Commercial',
            },
            preventiveMaintenanceDate: '2026-08-20',
        },
        assignedTowUnit: {
            unitNumber: '',
            unitClass: 'NA',
            unitType: 'NA',
            unitStatus: 'Not Assigned',
            description: '',
            physicalLocationCode: '',
            physicalCorp: '',
            owningLocationCode: '',
            hikeInfo: {
                hikeReqNumber: '',
                hikeStatus: '',
            },
            contractInfo: {
                contractId: '',
                dueInDate: '',
                contractStatus: '',
                contractType: '',
            },
            preventiveMaintenanceDate: '',
            source: '',
            owningCorp: '',
        },
        rentalType: 'Commercial',
        consumerCustomer: {
            firstName: 'Mark',
            lastName: 'Stevens',
            phoneNumber: '(480) 555-0119',
            email: 'mark.stevens@example.com',
            insuranceStatus: 'Inactive',
        },
        isCustomerContacted: false,
        cashDeposit: false,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: '',
    },

    {
        reservationId: '80201822',
        colorIndicator: '#a92323',
        paymentType: 'CC',
        plannerStatus: 'Active',
        reservationStatus: 'confirmed',
        tripType: 'oneway',
        leaseType: 'short',
        pickUp: {
            pickUpLocation: {
                corporation: 'HPTL',
                locationCode: '032114',
                locationType: 'Branch',
                locationName: 'Chicago',
                locationAddress: {
                    addressLine1: '1800 Lake Shore Dr',
                    addressLine2: '',
                    city: 'Chicago',
                    stateProvince: 'IL',
                    postalCode: '60601',
                    country: 'USA',
                },
                outboundCode: '555666',
                region: 'Midwest',
                utcOffset: -6,
                dayLight: true,
                regionName: 'Illinois',
                area: 'Metro',
                areaName: 'Chicago Metro',
                reportingLocationCode: '606099',
                reportingLocationName: 'Chicago Central',
                branch: '7788',
                branchName: 'Chicago',
                phoneNumber: '(312) 555-0190',
            },
            pickUpTime: '08:45:00',
            pickUpDate: '2026-02-28',
            pickUpUTCTimestamp: '2026-02-28 08:45:00.000',
        },
        dropOff: {
            dropOffLocation: {
                corporation: 'HPTL',
                locationCode: '044221',
                locationType: 'Branch',
                locationName: 'Detroit',
                locationAddress: {
                    addressLine1: '77 Motor Way',
                    addressLine2: '',
                    city: 'Detroit',
                    stateProvince: 'MI',
                    postalCode: '48201',
                    country: 'USA',
                },
                outboundCode: '443322',
                region: 'Midwest',
                utcOffset: -5,
                dayLight: true,
                regionName: 'Michigan',
                area: 'Metro',
                areaName: 'Detroit Metro',
                reportingLocationCode: '482011',
                reportingLocationName: 'Detroit Ops',
                branch: '8899',
                branchName: 'Detroit',
                phoneNumber: '(313) 555-0102',
            },
            expectedDropOffDate: '2026-09-04',
            expectedDropOffTime: '11:15:00',
            expectedDropOffUTCTimestamp: '2026-09-04 11:15:00.000',
        },
        assignedUnit: {
            unitNumber: 'IL-99001',
            unitClass: '1610',
            unitType: '4012',
            unitStatus: 'Not Assigned',
            source: 'Penske',
            unitDescription: "16' BOX TRUCK",
            owningLocationCode: '032114',
            owningCorp: 'HPTL',
            physicalLocationCode: '032114',
            physicalCorp: 'HPTL',
            hikeInfo: {
                hikeReqNumber: '77889900',
                hikeStatus: 'Completed',
            },
            contractInfo: {
                contractId: '11002233',
                dueInDate: '2026-09-04',
                contractStatus: 'Active',
                contractType: 'Consumer',
            },
            preventiveMaintenanceDate: '2026-09-08',
        },
        assignedTowUnit: {
            unitNumber: '11111',
            unitClass: '',
            unitType: '',
            unitStatus: 'Out-commercial',
            description: '',
            physicalLocationCode: '',
            physicalCorp: '',
            owningLocationCode: '',
            hikeInfo: {
                hikeReqNumber: '',
                hikeStatus: '',
            },
            contractInfo: {
                contractId: '',
                dueInDate: '',
                contractStatus: '',
                contractType: '',
            },
            preventiveMaintenanceDate: '',
            source: '',
            owningCorp: '',
        },
        rentalType: 'Consumer',
        consumerCustomer: {
            firstName: 'Lucas',
            lastName: 'Brown',
            phoneNumber: '(773) 555-0166',
            email: 'lucas.brown@example.com',
            insuranceStatus: 'Active',
        },
        isCustomerContacted: true,
        cashDeposit: false,
        tripTypeToolTip: '',
        rentalTypeToolTip: '',
        optionalEquipmentToolTip: '',
        optionalEquipment: 'Furniture Pads',
    },
];


